name: Maria Barbouletou
description: Ζωή σαν παραμύθι
markdown: kramdown
owner: Maria Barbouletou

gems:
  - jekyll-sitemap

social:
  facebook: https://www.facebook.com/maria.barb2

personal_info:
  email: mariabarbouletou@gmail.com
  mobile: (+30) 697 418 1052
  position: Μελιγού, Αρκαδία, Ελλάδα