name: Maria Barbouletou
description: Ζωή σαν παραμύθι
markdown: kramdown
owner: Maria Barbouletou
url: https://mariabarb.github.io

plugins:
  - jekyll-sitemap
  - jekyll-feed

tag_page_dir: blog/tag

social:
  facebook: https://www.facebook.com/maria.barb2
  pinterest: http://www.pinterest.com/mariabarb_
  linkedin: https://www.linkedin.com/in/maria-barbouletou-46aa55138

personal_info:
  email: mariabarbouletou@gmail.com
  mobile: (+30) 697 418 1052
  position: Μελιγού, Αρκαδία, Ελλάδα

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts